parameters:
  - name: environment
    displayName: environment
    type: string

jobs:
- deployment:
  displayName: 'Deployment'
  environment: ${{ parameters.environment }}
  strategy:
    runOnce:
      deploy:
        steps:
          - task: PowerShell@2
            displayName: 'Hello world'
            inputs:
              targetType: 'inline'
              script: |
                echo "hello world"
          - template: hello-world-job-2.yml
